#!/bin/bash

MANPAGE="collagegen.1.gz"
TARGET_PATH="/usr/local/share/man/man1/$MANPAGE"

if [[ $EUID -ne 0 ]]; then
    echo "Please run this script as root (e.g., sudo $0)"
    exit 1
fi

if [ -f "$TARGET_PATH" ]; then
    rm -f "$TARGET_PATH"
    echo "Removed man page: $TARGET_PATH"
else
    echo "No man page found at: $TARGET_PATH"
fi